import type { SourceManifest } from "@chilekit/core";

export const sourceManifests = [
  {
    id: "feriados",
    name: "Feriados legales de Chile",
    category: "feriados",
    official: false,
    auth: "none",
    formats: ["json"],
    freshness: "annual",
    status: "available",
    baseUrl: "https://api.boostr.cl/holidays",
    docsUrl: "https://docs.boostr.cl/reference/holidays-info",
    notes:
      "Usa API publica Boostr/FeriadosApp como fuente operativa no oficial; incluye fallback local 2026 para uso offline. El respaldo legal oficial debe trazarse via BCN.",
    tools: [
      { name: "get_holidays", description: "Lista feriados chilenos por año." },
      { name: "get_holiday", description: "Busca si una fecha ISO es feriado." },
    ],
  },
  {
    id: "territorio",
    name: "Division territorial de Chile",
    category: "territorio",
    official: false,
    auth: "none",
    formats: ["json", "csv"],
    freshness: "event-driven",
    status: "available",
    docsUrl: "https://github.com/piperubio/clregions",
    license: "MIT",
    notes:
      "Usa @clregions/data, que compila regiones, provincias y comunas desde fuentes oficiales y colaborativas como BCN/SIIT e ISO.",
    tools: [
      { name: "list_regions", description: "Lista regiones de Chile." },
      { name: "list_communes", description: "Lista comunas por region." },
      { name: "get_commune_info", description: "Busca comuna, provincia y region." },
    ],
  },
  {
    id: "mindicador",
    name: "mindicador.cl",
    category: "economia",
    official: false,
    auth: "none",
    formats: ["json"],
    freshness: "daily",
    status: "available",
    baseUrl: "https://mindicador.cl/api",
    docsUrl: "https://mindicador.cl/",
    notes: "Fuente publica no oficial usada para MVP sin credenciales.",
    tools: [{ name: "get_uf", description: "Obtiene UF por fecha." }],
  },
  {
    id: "banco-central",
    name: "Banco Central de Chile",
    category: "economia",
    official: true,
    auth: "optional",
    formats: ["json", "csv", "xml"],
    freshness: "daily",
    status: "manifest-only",
    docsUrl: "https://si3.bcentral.cl/Siete/ES/Siete/API",
    notes: "Fuente oficial para series economicas como IPC, UF, dolar observado y tasas.",
    tools: [
      { name: "get_uf", description: "Obtiene UF oficial." },
      { name: "get_dollar", description: "Obtiene tipo de cambio dolar observado." },
      { name: "search_series", description: "Busca series BDE." },
      { name: "get_series", description: "Obtiene observaciones de una serie BDE." },
    ],
  },
  {
    id: "datos-gob",
    name: "Portal de Datos Abiertos del Estado de Chile",
    category: "datos-abiertos",
    official: true,
    auth: "none",
    formats: ["json", "csv", "xml"],
    freshness: "unknown",
    status: "available",
    baseUrl: "https://datos.gob.cl/api/3/action",
    docsUrl: "https://datos.gob.cl/",
    tools: [{ name: "search_open_datasets", description: "Busca datasets en datos.gob.cl." }],
  },
  {
    id: "chilecompra",
    name: "Mercado Publico / ChileCompra",
    category: "compras-publicas",
    official: true,
    auth: "optional",
    formats: ["json", "xml"],
    freshness: "daily",
    status: "manifest-only",
    docsUrl: "https://api.mercadopublico.cl/",
    tools: [
      { name: "search_public_procurements", description: "Busca licitaciones y compras publicas." },
    ],
  },
  {
    id: "bcn",
    name: "Biblioteca del Congreso Nacional",
    category: "leyes",
    official: true,
    auth: "none",
    formats: ["html", "json", "xml"],
    freshness: "daily",
    status: "manifest-only",
    docsUrl: "https://www.bcn.cl/",
    tools: [{ name: "search_law", description: "Busca normas y legislacion." }],
  },
  {
    id: "ine",
    name: "Instituto Nacional de Estadisticas",
    category: "estadisticas",
    official: true,
    auth: "none",
    formats: ["csv", "json", "sdmx"],
    freshness: "monthly",
    status: "manifest-only",
    docsUrl: "https://www.ine.gob.cl/",
    tools: [{ name: "search_statistics", description: "Busca datasets y series INE." }],
  },
  {
    id: "servel",
    name: "Servicio Electoral de Chile",
    category: "elecciones",
    official: true,
    auth: "none",
    formats: ["csv", "json", "pdf"],
    freshness: "event-driven",
    status: "manifest-only",
    docsUrl: "https://www.servel.cl/",
    tools: [{ name: "search_election_data", description: "Busca estadisticas electorales." }],
  },
  {
    id: "sinca",
    name: "Sistema de Informacion Nacional de Calidad del Aire",
    category: "aire",
    official: true,
    auth: "none",
    formats: ["csv", "json"],
    freshness: "realtime",
    status: "manifest-only",
    docsUrl: "https://sinca.mma.gob.cl/",
    tools: [{ name: "search_air_quality", description: "Consulta calidad del aire." }],
  },
  {
    id: "cne",
    name: "Comision Nacional de Energia",
    category: "energia",
    official: true,
    auth: "none",
    formats: ["json", "csv"],
    freshness: "daily",
    status: "manifest-only",
    docsUrl: "https://api.cne.cl/",
    tools: [{ name: "search_fuel_prices", description: "Consulta precios de combustibles." }],
  },
  {
    id: "ide-chile",
    name: "IDE Chile / Geoportal de Chile",
    category: "geodatos",
    official: true,
    auth: "none",
    formats: ["geojson", "json", "xml"],
    freshness: "unknown",
    status: "manifest-only",
    docsUrl: "https://www.geoportal.cl/",
    tools: [{ name: "search_geodata", description: "Busca capas y recursos geoespaciales." }],
  },
  {
    id: "snifa",
    name: "Sistema Nacional de Informacion de Fiscalizacion Ambiental",
    category: "fiscalizacion",
    official: true,
    auth: "none",
    formats: ["csv", "json"],
    freshness: "weekly",
    status: "manifest-only",
    docsUrl: "https://snifa.sma.gob.cl/",
    tools: [
      {
        name: "search_environmental_enforcement",
        description: "Busca fiscalizaciones y sanciones.",
      },
    ],
  },
] satisfies SourceManifest[];

export function getSourceManifest(id: string): SourceManifest | undefined {
  return sourceManifests.find((source) => source.id === id);
}
